#!/bin/sh

url=""
quality=""
arguments=""
helperPath=`dirname "$0"`

#Function for getting arguments for the downloader
providearguments(){  
	arguments=`echo -e 'no\n-k 1M -x 5' |dmenu -i -nb '#2D303B' -nf white -sb blue -sf white -x 15 -y 40 -h 28 -w 545 -fn 'Terminus (TTF)-14' -p "arguments"`
	[[ $arguments = "" ]] && exit 0
}

#Function to select url from clipboard.
#greenclip is here a clipboard manager.
selecturl(){
	url=`greenclip print | xargs -0 | $helperPath/extract |dmenu -i -l 10 -nb '#2D303B' -nf white -sb blue -sf white -x 15 -y 40 -h 28 -w 545 -fn 'Terminus (TTF)-14' -p "Ссылка на видео: "`
	[[ $url = "" ]] && exit 0
}

#function to use youtube-dl to fetch quality of videos.
selectquality(){
	quality=`notify-send "Загрузка" "вариантов качества" | youtube-dl -F $url | \
	sed -n '7,50p' | \
	dmenu -i -l 10 -nb '#2D303B' -nf white -sb blue -sf white -x 15 -y 40 -h 28 -w 545 -fn 'Terminus (TTF)-14' -p "Качесто: " | \
	awk '{print $1;}'`
	[[ $quality = "" ]] && exit 0
}

main(){
	selecturl
	selectquality
	providearguments
	quality=`echo $quality | sed 's/ /+/'`
	if [[ $arguments = "no" ]]
		then
			youtube-dl -f $quality --external-downloader aria2c $url
	else
		echo "$arguments"
		youtube-dl -f $quality --external-downloader aria2c --external-downloader-args "$arguments" $url
	fi
}

main
