#!/bin/sh

# vim: filetype=transmission
#  ____  _____ ______     _____ ____ _____   _____ ___   ____  ____ _     _____ 
# / ___|| ____|  _ \ \   / /_ _/ ___| ____| |_   _/ _ \ / ___|/ ___| |   | ____|
# \___ \|  _| | |_) \ \ / / | | |   |  _|     | || | | | |  _| |  _| |   |  _|  
#  ___) | |___|  _ < \ V /  | | |___| |___    | || |_| | |_| | |_| | |___| |___ 
# |____/|_____|_| \_\ \_/  |___\____|_____|   |_| \___/ \____|\____|_____|_____|
#
# Скрипт проверки активности сервиса
# Написан: @alexandrovich.ff
# Website: http://malikov.red

if pgrep -x transmission-da >/dev/null ;
then
	[ "$(printf "Нет\\nДа" | dmenu -nb '#2D303B' -nf white -sb blue -sf white -x 15 -y 40 -h 28 -w 545 -fn 'Terminus (TTF)-14' -i -p "Остановить торрент службу?")" = "Да" ] && killall transmission-da && notify-send "💡 Служба [Transmission]: остановлена"
else
	~/.config/i3/scripts/ifinstalled transmission-cli || exit
	[ "$(printf "Нет\\nДа" | dmenu -nb '#2D303B' -nf white -sb blue -sf white -x 15 -y 40 -h 28 -w 545 -fn 'Terminus (TTF)-14' -i -p "Запустить торрент службу?")" = "Да" ] && transmission-daemon && notify-send "💡 Служба [Transmission]: запущена."
fi
