#!/bin/sh

# vim: filetype=dmenu
#  ____  __  __ _____ _   _ _   _       _____ __  __  ___      _ ___ 
# |  _ \|  \/  | ____| \ | | | | |     | ____|  \/  |/ _ \    | |_ _|
# | | | | |\/| |  _| |  \| | | | |_____|  _| | |\/| | | | |_  | || | 
# | |_| | |  | | |___| |\  | |_| |_____| |___| |  | | |_| | |_| || | 
# |____/|_|  |_|_____|_| \_|\___/      |_____|_|  |_|\___/ \___/|___|
#
# Скрипт выбора смайликов emoji
# Написан: @alexandrovich.ff
# Website: http://malikov.red

xclip -h >/dev/null || exit

chosen=$(grep -v "#" ~/.config/i3/scripts/emoji | dmenu -nb '#2D303B' -nf white -sb blue -sf white -x 15 -y 40 -h 28 -w 545 -fn 'Terminus (TTF)-14' -i -l 20 -fn Monospace-12)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' скопировано в буфер обмена." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' скопировано." &