#!/usr/bin/env sh

# vim: filetype=polybar
#  ____   ___  _  __   ______    _    ____  
# |  _ \ / _ \| | \ \ / / __ )  / \  |  _ \ 
# | |_) | | | | |  \ V /|  _ \ / _ \ | |_) |
# |  __/| |_| | |___| | | |_) / ___ \|  _ < 
# |_|    \___/|_____|_| |____/_/   \_\_| \_\
#
# Конфигурационный файл для нижнего бара
# Написан: @alexandrovich.ff
# Website: http://malikov.red

killall -q polybar
killall -q bash