#!/bin/bash

# vim: filetype=rofi
#   ____ ___  _     ___  ____  ____  
#  / ___/ _ \| |   / _ \|  _ \|  _ \ 
# | |  | | | | |  | | | | |_) | | | |
# | |__| |_| | |__| |_| |  _ <| |_| |
#  \____\___/|_____\___/|_| \_\____/ 
#
# Темная цветовая тема
# Написан: @alexandrovich.ff
# Website: http://malikov.red

SDIR="$HOME/.config/polybar/scripts"

MENU="$(rofi -theme $HOME/.config/rofi/dark.rasi -sep "|" -dmenu -i -p 'Темная цветовая схема' -location 5 -columns 2 -xoffset -50 -yoffset -450 -width 30 -hide-scrollbar -line-padding 4 -padding 20 -lines 10 <<< " Янтарная| Синяя| Сине-серая| Коричневая| Циан| Темно-оранжевая| Темно-пурпурная| Зеленая| Серая| Индиго| Светло-синяя| Светло-зеленая| Лаймовая| Оранжевая| Розовая| Пурпурная| Красная| Сине-зеленая| Желтая")"
            case "$MENU" in
                *Янтарная) $SDIR/color-dark -amber ;;
                *Синяя) $SDIR/color-dark -blue ;;
                *Сине-серая) $SDIR/color-dark -blue-grey ;;
                *Коричневая) $SDIR/color-dark -brown ;;
                *Циан) $SDIR/color-dark -cyan ;;
                *Темно-оранжевая) $SDIR/color-dark -deep-orange ;;
                *Темно-пурпурная) $SDIR/color-dark -deep-purple ;;
                *Зеленая) $SDIR/color-dark -green ;;
                *Серая) $SDIR/color-dark -grey ;;
                *Индиго) $SDIR/color-dark -indigo ;;
                *Светло-синяя) $SDIR/color-dark -light-blue ;;
                *Светло-зеленая) $SDIR/color-dark -light-green ;;
                *Лаймовая) $SDIR/color-dark -lime ;;
                *Оранжевая) $SDIR/color-dark -orange ;;
                *Розовая) $SDIR/color-dark -pink ;;
                *Пурпурная) $SDIR/color-dark -purple ;;
                *Красная) $SDIR/color-dark -red ;;
                *Сине-зеленая) $SDIR/color-dark -teal ;;
                *Желтая) $SDIR/color-dark -yellow              
            esac
