#!/bin/bash

# vim: filetype=rofi
#   ____ ___  _     ___  ____  ____  
#  / ___/ _ \| |   / _ \|  _ \|  _ \ 
# | |  | | | | |  | | | | |_) | | | |
# | |__| |_| | |__| |_| |  _ <| |_| |
#  \____\___/|_____\___/|_| \_\____/ 
#
# Светлая цветовая тема
# Написан: @alexandrovich.ff
# Website: http://malikov.red

SDIR="$HOME/.config/polybar/scripts"

MENU="$(rofi -theme $HOME/.config/rofi/light.rasi -sep "|" -dmenu -i -p 'Светлая цветовая схема' -location 5 -columns 2 -xoffset -50 -yoffset -450 -width 30 -hide-scrollbar -line-padding 4 -padding 20 -lines 10 <<< " Янтарная| Синяя| Сине-серая| Коричневая| Циан| Темно-оранжевая| Темно-пурпурная| Зеленая| Серая| Индиго| Светло-синяя| Светло-зеленая| Лаймовая| Оранжевая| Розовая| Пурпурная| Красная| Сине-зеленая| Желтая")"
            case "$MENU" in
                *Янтарная) $SDIR/color-light -amber ;;
                *Синяя) $SDIR/color-light -blue ;;
                *Сине-серая) $SDIR/color-light -blue-grey ;;
                *Коричневая) $SDIR/color-light -brown ;;
                *Циан) $SDIR/color-light -cyan ;;
                *Темно-оранжевая) $SDIR/color-light -deep-orange ;;
                *Темно-пурпурная) $SDIR/color-light -deep-purple ;;
                *Зеленая) $SDIR/color-light -green ;;
                *Серая) $SDIR/color-light -grey ;;
                *Индиго) $SDIR/color-light -indigo ;;
                *Светло-синяя) $SDIR/color-light -light-blue ;;
                *Светло-зеленая) $SDIR/color-light -light-green ;;
                *Лаймовая) $SDIR/color-light -lime ;;
                *Оранжевая) $SDIR/color-light -orange ;;
                *Розовая) $SDIR/color-light -pink ;;
                *Пурпурная) $SDIR/color-light -purple ;;
                *Красная) $SDIR/color-light -red ;;
                *Сине-зеленая) $SDIR/color-light -teal ;;
                *Желтая) $SDIR/color-light -yellow            
            esac
