#!/bin/bash

# vim: filetype=rofi
#   ____ ___  _     ___  ____  ____  
#  / ___/ _ \| |   / _ \|  _ \|  _ \ 
# | |  | | | | |  | | | | |_) | | | |
# | |__| |_| | |__| |_| |  _ <| |_| |
#  \____\___/|_____\___/|_| \_\____/ 
#
# Темная цветовая тема
# Написан: @alexandrovich.ff
# Website: http://malikov.red

PDIR="$HOME/.config/polybar"
RDIR="$HOME/.config/rofi"
I3DIR="$HOME/.config/i3"
GTK3DIR="$HOME/.config/gtk-3.0"
CURSORDIR="$HOME/.icons/default"
GTK2DIR="$HOME"
POLYUPD="$HOME/.config/polybar/scripts"
SUBLDIR="$HOME/.config/sublime-text-3/Packages/User"

LAUNCH="i3-msg restart"
 
if  [[ $1 = "-amber" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #ffb300/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #ffb300/g' $PDIR/colors
sed -i -e 's/be = .*/be = #ffb300/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-blue" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #1e88e5/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #1e88e5/g' $PDIR/colors
sed -i -e 's/be = .*/be = #1e88e5/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-blue-grey" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #546e7a/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #546e7a/g' $PDIR/colors
sed -i -e 's/be = .*/be = #546e7a/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-brown" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #6d4c41/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #6d4c41/g' $PDIR/colors
sed -i -e 's/be = .*/be = #6d4c41/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-cyan" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #00acc1/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #00acc1/g' $PDIR/colors
sed -i -e 's/be = .*/be = #00acc1/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-deep-orange" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #f4511e/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #f4511e/g' $PDIR/colors
sed -i -e 's/be = .*/be = #f4511e/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-deep-purple" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #5e35b1/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #5e35b1/g' $PDIR/colors
sed -i -e 's/be = .*/be = #5e35b1/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-green" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #43a047/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #43a047/g' $PDIR/colors
sed -i -e 's/be = .*/be = #43a047/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-grey" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #757575/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #757575/g' $PDIR/colors
sed -i -e 's/be = .*/be = #757575/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-indigo" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #3949ab/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #3949ab/g' $PDIR/colors
sed -i -e 's/be = .*/be = #3949ab/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-light-blue" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #039be5/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #039be5/g' $PDIR/colors
sed -i -e 's/be = .*/be = #039be5/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-light-green" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #7cb342/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #7cb342/g' $PDIR/colors
sed -i -e 's/be = .*/be = #7cb342/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-lime" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #c0ca33/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #c0ca33/g' $PDIR/colors
sed -i -e 's/be = .*/be = #c0ca33/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #252525/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-orange" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #fb8c00/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #fb8c00/g' $PDIR/colors
sed -i -e 's/be = .*/be = #fb8c00/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-pink" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #d81b60/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #d81b60/g' $PDIR/colors
sed -i -e 's/be = .*/be = #d81b60/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-purple" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #8e24aa/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #8e24aa/g' $PDIR/colors
sed -i -e 's/be = .*/be = #8e24aa/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-red" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #e53935/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #e53935/g' $PDIR/colors
sed -i -e 's/be = .*/be = #e53935/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-teal" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #00897b/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #00897b/g' $PDIR/colors
sed -i -e 's/be = .*/be = #00897b/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #f5f5f5/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

elif  [[ $1 = "-yellow" ]]; then
# Цветовая схема
sed -i -e 's/bg = .*/bg = #2D303B/g' $PDIR/colors
sed -i -e 's/fg = .*/fg = #f5f5f5/g' $PDIR/colors
sed -i -e 's/ac = .*/ac = #fdd835/g' $PDIR/colors
sed -i -e 's/bi = .*/bi = #fdd835/g' $PDIR/colors
sed -i -e 's/be = .*/be = #fdd835/g' $PDIR/colors
sed -i -e 's/mf = .*/mf = #252525/g' $PDIR/colors

sed -i -e 's/light/dark/g' $RDIR/config
sed -i -e 's/termite-light.color/termite-dark.color/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-dl
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuyoutube/youtube-music
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/config
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenudisplay
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-youtube
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenusearch-moonwalk
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuumount
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenurecord
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuresize
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuscreenshot
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuunicode
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenuman
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/dmenupass
sed -i -e 's/-nb white -nf black -sb red -sf white/-nb '\'#2D303B\'' -nf white -sb blue -sf white/g' $I3DIR/scripts/transmission/toggle
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/lupdates
sed -i -e 's/termite-light.color/termite-dark.color/g' $POLYUPD/network
sed -i -e 's/termite-light.color/termite-dark.color/g' $HOME/.profile
sed -i -e 's/gtk-theme-name=Numix/gtk-theme-name=Arc-Dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-theme-name="Numix"/gtk-theme-name="Arc-Dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-icon-theme-name=Numix-Square/gtk-icon-theme-name=zafiro-icon-theme/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-icon-theme-name="Numix-Square"/gtk-icon-theme-name="zafiro-icon-theme"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/gtk-cursor-theme-name=capitaine-cursors-light/gtk-cursor-theme-name=capitaine-cursors-dark/g' $GTK3DIR/settings.ini
sed -i -e 's/gtk-cursor-theme-name="capitaine-cursors-light"/gtk-cursor-theme-name="capitaine-cursors-dark"/g' $GTK2DIR/.gtkrc-2.0
sed -i -e 's/Inherits=capitaine-cursors-light/Inherits=capitaine-cursors-dark/g' $CURSORDIR/index.theme
sed -i -e 's/"theme": "Default.sublime-theme"/"theme": "One Dark.sublime-theme"/g' $SUBLDIR/Preferences.sublime-settings
sed -i -e 's/set background=light/set background=dark/g' $HOME/.config/nvim/init.vim
# Перезапуск polybar
$LAUNCH &

else
echo "Available options:
-amber		-blue			-blue-grey		-brown
-cyan		-deep-orange	-deep-purple	-green
-grey		-indigo			-light-blue		-light-green
-lime		-orange			-pink			-purple
-red		-teal			-yellow"
fi
