#!/bin/bash

# vim: filetype=polybar
#  _   _ ____  ____    _  _____ _____ ____  
# | | | |  _ \|  _ \  / \|_   _| ____/ ___| 
# | | | | |_) | | | |/ _ \ | | |  _| \___ \ 
# | |_| |  __/| |_| / ___ \| | | |___ ___) |
#  \___/|_|   |____/_/   \_\_| |_____|____/ 
#
# Запуск обновления системы
# Написан: @alexandrovich.ff
# Website: http://malikov.red

termite -c $HOME/.config/termite/termite-dark.color -t "Обновления" -e $HOME/.scripts/updates
