#!/bin/bash

# vim: filetype=polybar
#  _____ ____      _    _   _ ____  __  __ ___ ____ ____ ___ ___  _   _ 
# |_   _|  _ \    / \  | \ | / ___||  \/  |_ _/ ___/ ___|_ _/ _ \| \ | |
#   | | | |_) |  / _ \ |  \| \___ \| |\/| || |\___ \___ \| | | | |  \| |
#   | | |  _ <  / ___ \| |\  |___) | |  | || | ___) |__) | | |_| | |\  |
#   |_| |_| \_\/_/   \_\_| \_|____/|_|  |_|___|____/____/___\___/|_| \_|
#
# Скрипт - статус торрент [Transmission]
# Написан: @alexandrovich.ff
# Website: http://malikov.red

if pgrep -x transmission-da >/dev/null ;
then
    transmission-remote -l | grep % |
        sed "
        s/.*Stopped.*/A/g;
        s/.*Seeding.*/Z/g;
        s/.*100%.*/N/g;
        s/.*Idle.*/B/g;
        s/.*Uploading.*/L/g;
        s/.*%.*/M/g" |
            sort -h | uniq -c | sed "
                    s/A/🛑/g;
                    s/B/⌛️/g;
                    s/L/🔼/g;
                    s/M/🔽/g;
                    s/N/✅/g;
                    s/Z/🌱/g" | awk '{print $2, $1}' | tr '\n' ' ' | sed -e "s/ $//g"

    case $BLOCK_BUTTON in
        1) $TERMINAL -e transmission-remote-cli ;;
        3) pgrep -x dunst >/dev/null && notify-send "Torrent module" "🛑: paused
    ⏳: idle (seeds needed)
    🔼: uploading (unfinished)
    🔽: downloading
    ✅: done
    🌱: done and seeding" ;;
    esac
else
    echo ""
fi